server:
  port: 8083
spring:
  application:
    name: search-service
  elasticsearch:
    rest:
      uris: http://localhost:9200
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15