server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///mall?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 991228
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.user.pojo