server:
  port: 10010
spring:
  application:
    name: leyou-getway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
    search-service: /search/** #路由到搜索的微服务
    user-service: /user/** #路由到用户的微服务
    auth-service: /auth/** #路由到授权中心的微服务
    cart-service: /cart/** #路由到购物车的微服务
    order-service: /order/** #路由到订单的微服务
  add-host-header: true
  sensitive-headers: #覆盖敏感头信息，使cookie可以正常写入
leyou:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item